Django-RealEstate/accounts/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import (login, register, logout, dashboard, password_reset_request,
                    ProfileUpdateView, AddressView)

urlpatterns = [
    path('login', login, name='login'),
    path('register', register, name='register'),
    path('logout', logout, name='logout'),
    path('dashboard', dashboard, name='dashboard'),
    path('profile/<int:pk>', login_required(
         ProfileUpdateView.as_view()), name='profile'),
    path('profile/address', login_required(  # TODO move to coreapp?
         AddressView.as_view()), name='user-address'),
    path("password-reset", password_reset_request, name="password-reset")
]

Django-RealEstate/core/urls.py
from django.urls import path

from .views import (IndexView, AboutView, ContactView, ImpressumView, PrivacyView, policyView, termsView, Gallaryview,
                    RobotsTXTView)

urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    path('robots.txt', RobotsTXTView.as_view(content_type="text/plain")),
    path('contact-us', ContactView.as_view(), name='contact'),
    path('about-us', AboutView.as_view(), name='about'),
    path('impressum', ImpressumView.as_view(), name="impressum"),
    path('privacy', PrivacyView.as_view(), name="privacy"),
    path('policy', policyView.as_view(), name="policy"),
    path('terms', termsView.as_view(), name="terms"),
    path('gallary', Gallaryview.as_view(), name="gallary"),

]

Django-RealEstate/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from contacts.views import AdminContactView
from django.contrib.auth import views as auth_views
# from django.conf.urls import (handler400, handler403, handler404, handler500)

handler400 = 'core.views.bad_request'
handler403 = 'core.views.permission_denied'
handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'


urlpatterns = i18n_patterns(
    path('i18n/', include('django_translation_flags.urls')),
    path('admin/', admin.site.urls),
    path('admin/contact/', AdminContactView.as_view(), name='admin-contact'),

    path('', include('core.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('password-reset/done/', auth_views.PasswordResetDoneView.as_view(
        template_name='accounts/auth/password_reset_done.html'),
         name='password-reset-done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(  # noqa
        template_name="accounts/auth/password_reset_confirm.html"),
         name='password-reset-confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/auth/password_reset_complete.html'),
         name='password_reset_complete'),

    path('listings/', include('listings.urls')),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('allauth.urls')),
    path('contacts/', include('contacts.urls')),
    path('listings/', include('documents.urls')),

)


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

Django-RealEstate/accounts/models.py
from django.db import models
from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.utils.translation import gettext_lazy as _
from django.urls import reverse




class CustomUserManager(BaseUserManager):
    """
    Custom user model manager where email is the unique identifiers
    for authentication instead of usernames.
    """

    def create_user(self, email, password, **extra_fields):
        """
        Create and save a User with the given email and password.
        """
        if not email:
            raise ValueError(_("The Email must be set"))
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save()
        return user

    def create_superuser(self, email, password, **extra_fields):
        """
        Create and save a SuperUser with the given email and password.
        """
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError(_("Superuser must have is_staff=True."))
        if extra_fields.get('is_superuser') is not True:
            raise ValueError(_("Superuser must have is_superuser=True."))
        return self.create_user(email, password, **extra_fields)



class CustomUser(AbstractUser):
    first_name = models.CharField(max_length=255, null=True,
                                  verbose_name=_("Firstname"))
    last_name = models.CharField(max_length=255, null=True,
                                 verbose_name=_("Lastname"))
    username = None
    phone = models.CharField(max_length=20, null=True,
                             verbose_name=_("Phone"))
    address = models.ForeignKey('core.Address', null=True, blank=True,
                                on_delete=models.DO_NOTHING,
                                verbose_name=_("Address"))
    email = models.EmailField(unique=True, verbose_name=_("Email"))

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    def get_absolute_url(self):
        return reverse('profile', args=[str(self.id)])

    def get_groups(self):
        return [group.name for group in self.groups.all()]
    get_groups.short_description = _("Groups")


class Realtor(models.Model):
    name = models.CharField(max_length=200)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.PROTECT)
    photo = models.ImageField(upload_to='realtors/profile/',
                              verbose_name=_("Photo"))
    description = models.TextField(blank=True,
                                   verbose_name=_("Description"))
    phone = models.CharField(max_length=20, verbose_name=_("Phone"))
    email = models.CharField(max_length=50)
    is_mvp = models.BooleanField(default=False)
    hire_date = models.DateField(null=True,
                                 verbose_name=_("Hire date"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Realtor")
        verbose_name_plural = _("Realtors")

Django-RealEstate/contacts/models.py
from django.db import models
from datetime import datetime
from django.conf import settings
from django.utils.translation import gettext_lazy as _



class Contact(models.Model):
    listing = models.ForeignKey('listings.Listing',
                                on_delete=models.DO_NOTHING,
                                verbose_name=_("Listing"))
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.PROTECT, verbose_name=_("User"))
    phone = models.CharField(max_length=100, verbose_name=_("Phone"))
    message = models.TextField(blank=True, verbose_name=_("Message"))
    contact_date = models.DateTimeField(default=datetime.now, blank=True,
                                        verbose_name=_("Contact date"))
    can_access_documents = models.BooleanField(default=False,
                                               verbose_name=_("Docs access"))

    class Meta:
        ordering = ['-contact_date']

    def __str__(self):
        return f"{self.listing} - {self.user}"

    def get_full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"
    get_full_name.short_description = _("Client")

    def get_email(self):
        return f"{self.user.email}"
    get_email.short_description = _("Email")



class ChatMessage(models.Model):
    contact = models.ForeignKey(Contact, on_delete=models.PROTECT,
                                verbose_name=_("Contact listing"))
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.PROTECT, verbose_name=_("User"))
    message = models.TextField(null=True, blank=False)
    timestamp = models.DateTimeField(default=datetime.now, blank=True,
                                     verbose_name=_("Date and iime"))

    class Meta:
        ordering = ['-timestamp']

    def __str__(self):
        return f"{self.contact} - {self.user} - {self.message}"

Django-RealEstate/accounts/forms.py
from django import forms
from .models import CustomUser
from django.utils.translation import gettext_lazy as _


class BasicFormStyle(forms.ModelForm):
    """define the base and the form name"""

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for key, field in self.fields.items():
            field.widget.attrs['class'] = "form-control"


class ProfileUpdateForm(BasicFormStyle):

    class Meta():
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'phone', 'last_login']
        widgets = {
            'first_name': forms.TextInput(attrs={'placeholder': _("Firstname"),
                                                 'name': 'first_name',
                                                 'type': 'text',
                                                 'aria-required': 'true',
                                                 'minlength': '2'}),
            'last_name': forms.TextInput(attrs={'placeholder': _("Lastname"),
                                                'name': 'last_name',
                                                'type': 'text',
                                                'aria-required': 'true',
                                                'minlength': '2'}),
            'email': forms.TextInput(attrs={'placeholder': _("Email"),
                                            'name': 'email',
                                            'type': 'email',
                                            'aria-required': 'true',
                                            'minlength': '2'}),
            'phone': forms.TextInput(attrs={'placeholder': _("Phone"),
                                            'name': 'phone',
                                            'type': 'phone',
                                            'aria-required': 'true',
                                            'minlength': '2'}),

        }

Django-RealEstate/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib import messages, auth
from django.views.generic import (UpdateView, TemplateView)
from django.contrib.messages.views import SuccessMessageMixin
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse
from django.contrib.auth.forms import PasswordResetForm
# from django.contrib.auth.models import User
from django.template.loader import render_to_string
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes

from .forms import ProfileUpdateForm
from .models import CustomUser
from contacts.models import Contact

from django.contrib.auth import get_user_model


User = get_user_model()


def register(request):
    """Register new user function"""
    context = {
        'title': _("Register"),
        'page_title': _("Register Account"),
        'page_description': _("Real estate manager. "
                              "This is the regitration page."),
    }

    if request.method == 'POST':
        # Get form values
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        email = request.POST['email']
        password = request.POST['password']
        password2 = request.POST['password2']

        # Check if passwords match
        if password == password2:
            # Check email
            if User.objects.filter(email=email).exists():
                messages.error(request, _("That email is being used"))
                return redirect('register')
            else:
                # if everything looks good
                user = User.objects.create_user(
                    password=password, email=email, is_active=True,
                    first_name=first_name, last_name=last_name)
                user.save()
                messages.success(
                    request, _("You are now registered and can log in"))
                return redirect('login')
        else:
            messages.error(request, _("Passwords do not match"))
            return redirect('register')
    else:
        return render(request, 'accounts/auth/register.html', context)


def login(request):
    """Login user function"""
    context = {
        'title': _("Login"),
        'page_title': _("Account Login"),
        'page_description': _("Real estate manager. This is the login page."),
    }
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']

        user = auth.authenticate(email=email, password=password)
        if user is not None:
            auth.login(request, user)
            messages.success(request, _("You are now logged in"))
            return redirect('dashboard')
        else:
            messages.error(request, _("Invalid credentials"))
            return redirect('login')
    else:
        return render(request, 'accounts/auth/login.html', context)


def logout(request):
    """Logout user function"""
    if request.method == 'POST':
        auth.logout(request)
        messages.success(request, _("You are now logged out"))
        return redirect('index')


def password_reset_request(request):
    if request.method == "POST":
        password_reset_form = PasswordResetForm(request.POST)
        if password_reset_form.is_valid():
            data = password_reset_form.cleaned_data['email']
            associated_users = User.objects.filter(Q(email=data))
            if associated_users.exists():
                for user in associated_users:
                    subject = "Password Reset Requested"
                    email_template_name = "accounts/auth/password_reset_email.txt"  # noqa
                    c = {
                        "email": user.email,
                        'domain': 'real.lex.tornode.org',
                        'site_name': 'Bangla Villageg - Real Estate',
                        "uid": urlsafe_base64_encode(force_bytes(user.pk)),
                        "user": user,
                        'token': default_token_generator.make_token(user),
                        'protocol': 'https',
                    }
                    email = render_to_string(email_template_name, c)
                    try:
                        send_mail(subject, email, 'schonefeld.dev@gmail.com',
                                  [user.email], fail_silently=False)
                    except BadHeaderError:
                        return HttpResponse('Invalid header found.')
                    return redirect("password-reset-done")
    password_reset_form = PasswordResetForm()
    context = {
        'password_reset_form': PasswordResetForm(),
        'title': _("Reset Password"),
        'page_title': _("Password reset request"),
        'page_description': _("Real estate manager. "
                              "This is the password reset request page."),
    }
    return render(request=request, context=context,
                  template_name="accounts/auth/password_reset.html")


class ProfileUpdateView(SuccessMessageMixin, UpdateView):
    model = CustomUser
    form_class = ProfileUpdateForm
    template_name = 'accounts/profile.html'
    success_message = _("Profile updated successfully!")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # request.path replacement
        context['profile'] = True
        # Showcase Section Infos
        context['title'] = _("Manage Account")
        context['subtitle'] = _("Manage your Real-Estate account")
        # SEO
        context['page_title'] = _("Impressum")
        context['page_description'] = _("Real estate manager."
                                        "This is our impressum page.")

        return context


class AddressView(TemplateView):
    template_name = 'accounts/address.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['address'] = True
        return context


# TODO convert to class based view
def dashboard(request):
    user_contacts = Contact.objects.order_by('-contact_date').filter(
        user_id=request.user.id)

    context = {
        'contacts': user_contacts
    }
    return render(request, 'accounts/dashboard.html', context)

Django-RealEstate/templates/accounts/address.html
{% extends 'core/base.html' %}
{% load static %}

{% block title %} | Address {% endblock %}

{% block content %}

{% include 'core/partials/_showcase_section.html' %}


<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'index' %}">
            <i class="fas fa-home"></i> {{ _("Home") }}</a>
        </li>
        <li class="breadcrumb-item"> {{ _("Profile") }}</li>
        <li class="breadcrumb-item active"> {{ _("Address") }}</li>

      </ol>
    </nav>
  </div>
</section>

<!-- Alerts -->
{% include 'core/partials/_alerts.html' %}

<section id="dashboard" class="py-4">
  <div class="container">
    {% include 'accounts/_partials/profile-navbar.html' %}
    <div class="pb-3 pt-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ _("Address") }}</h5>
          <hr>
          <form method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <ul class="errorlist">
              {% for key, value in form.errors.items %}
              <li class="text-danger">{{ value }}</li>
              {% endfor %}
            </ul>

            <div class="form-row">
              <div class="form-group col-md-6">
                <label>{{ form.street.label }}</label>
                <div>{{ form.street }}</div>
                <p class="text-danger">{{ form.street.errors }}</p>
              </div>

              <div class="form-group col-md-6">
                <label>{{ form.hn.label }}</label>
                <div>{{ form.hn }}</div>
                <p class="text-danger">{{ form.hn.errors }}</p>
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-6">
                <label>{{ form.zipcode.label }}</label>
                <div>{{ form.zipcode }}</div>
                <p class="text-danger">{{ form.zipcode.errors }}</p>
              </div>

              <div class="form-group col-md-6">
                <label>{{ form.city.label }}</label>
                <div>{{ form.city }}</div>
                <p class="text-danger">{{ form.city.errors }}</p>
              </div>
            </div>
            {% include 'core/partials/btn_save_back.html' %}
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

Django-RealEstate/templates/accounts/dashboard.html
{% extends 'core/base.html' %}
{% load static %}
{% load filters %}

{% block extrastyle %}
<meta name="description" content="Real estate manager.
    This is the dashboard. You can manage your listings, documents and history here."/>
{% endblock %}
{% block title %} | User Dashboard {% endblock %}

{% block content %}
<section id="showcase-inner" class="py-5 showcase-text">
  <div class="container bg-blur">
    <div class="row">
      <div class="col-md-12 my-5">
        <h1 class="display-4 my-5 showcase-text">
          {{ _("Dashboard") }}
        </h1>
        <p class="lead ">{{ _("Manage your Real-Estate account") }}</p>
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'index' %}">
            <i class="fas fa-home"></i> {{ _("Home") }}</a>
        </li>
        <li class="breadcrumb-item active"> {{ _("Dashboard") }}</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Alerts -->
{% include 'core/partials/_alerts.html' %}







<section id="dashboard" class="py-4">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h2>{{ _("Welcome") }} {{ user.first_name }}</h2>
        <p>{{ _("Here are the property listings that you have inquired about") }}</p>

        {% if contacts %}
        <table class="table">
          <thead>
            <tr>
              <th>{{ _("Property") }}</th>
              <th>{{ _("Date") }}</th>
              <th>{{ _("Action") }}</th>
            </tr>
          </thead>
          <tbody>
            {% for contact in contacts %}
            <tr>
              <td>{{ contact.listing }}</td>
              <td>{{ contact.contact_date|date:"d M Y" }}</td>
              <td>
                <div class="row col-12 px-0">
                  <div class="col-12 col-md-6 col-lg-4 mb-1">
                    {% if contact.can_access_documents %}
                    <a class="btn btn-secondary btn-block"" href="{% url 'documents' contact.listing.id %}">
                      <i class="fas fa-folder-open"></i>
                      {{ _("Files") }}
                      ({{ contact.listing.id|get_nr_docs }}) </a>
                    {% endif %}
                  </div>
                  <div class="col-12 col-md-6 col-lg-4 mb-1 ">
                    <a class="btn btn-outline-primary btn-block"" href="{% url 'listing' contact.listing_id %}">
                      <i class="fas fa-eye"></i>
                      {{ _("Listing") }}
                    </a>
                  </div>

                  <div class="col-12 col-md-6 col-lg-4 mb-1">
                    {% if contact.chatmessage_set.all.count > 0 %}
                    <a class="btn btn-outline-secondary btn-block" href="{% url 'chat-history' contact.id %}">
                      <i class="fas fa-eye"></i>
                      {{ _("History") }}
                    </a>
                    {% endif %}
                  </div>
                </div>

              </td>

            </tr>
            {% endfor %}
          </tbody>
        </table>

        {% else %}
        <p>{{ _("You have not made any inquiries") }}</p>
        {% endif %}
      </div>
    </div>
  </div>
</section>
{% endblock %}

Django-RealEstate/templates/accounts/profile.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block extrastyle %}
<meta name="description" content="Real estate manager.
    This is your profile. Here you can manage your personal data, your address and your documents." />
{% endblock %}

{% block title %} | Profile {% endblock %}

{% block content %}

{% include 'core/partials/_showcase_section.html' %}

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="{% url 'index' %}">
            <i class="fas fa-home"></i> {{ _("Home") }}</a>
        </li>
        <li class="breadcrumb-item active"> {{ _("Profile") }}</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Alerts -->
{% include 'core/partials/_alerts.html' %}

<section id="dashboard" class="py-4">
  <div class="container">

    <div class="pb-3 pt-3">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ _("Profile Information") }}</h5>
          <h6 class="card-subtitle mb-2 text-muted">{{ _("Last login") }}: {{ user.last_login }}</h6>
          <hr>
          <form method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <ul class="errorlist">
              {% for key, value in form.errors.items %}
              <li class="text-danger">{{ value }}</li>
              {% endfor %}
            </ul>

            <div class="form-row">
              <div class="form-group col-md-6">
                <label>{{ form.first_name.label }}</label>
                <div>{{ form.first_name }}</div>
                <p class="text-danger">{{ form.first_name.errors }}</p>
              </div>

              <div class="form-group col-md-6">
                <label>{{ form.last_name.label }}</label>
                <div>{{ form.last_name }}</div>
                <p class="text-danger">{{ form.last_name.errors }}</p>
              </div>
            </div>

            <div class="form-row">
              <div class="form-group col-md-6">
                <label>{{ form.email.label }}</label>
                <div>{{ form.email }}</div>
                <p class="text-danger">{{ form.email.errors }}</p>
              </div>

              <div class="form-group col-md-6">
                <label>{{ form.phone.label }}</label>
                <div>{{ form.phone }}</div>
                <p class="text-danger">{{ form.phone.errors }}</p>
              </div>
            </div>
            {% include 'core/partials/btn_save_back.html' %}
          </form>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}